[theme]

# Primary accent for interactive elements
primaryColor = '#434770'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F0F2F6'

# Color used for almost all text
textColor = '#434770'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[ui]
hideTopBar = true